import Vue from "vue/dist/vue.js";

import WgDescExample from "./wg-desc-example/wg-desc-example.vue";
Vue.component("wg-desc-example", WgDescExample);
import WgSlider from "./wg-slider/wg-slider.vue";
Vue.component("wg-slider", WgSlider);
import WgSliderNavig from "./wg-slider/wg-slider-navig.vue";
Vue.component("wg-slider-navig", WgSliderNavig);
import WgSliderZoom from "./wg-slider/wg-slider-zoom.vue";
Vue.component("wg-slider-zoom", WgSliderZoom);
import WgCardAd from "./wg-cards/wg-card-ad.vue";
Vue.component("wg-card-ad", WgCardAd);
import WgCardPhoto from "./wg-cards/wg-card-photo.vue";
Vue.component("wg-card-photo", WgCardPhoto);
import WgComments from "./wg-comments/wg-comments.vue";
Vue.component("wg-comments", WgComments);
import WgComment from "./wg-comments/wg-comment.vue";
Vue.component("wg-comment", WgComment);
import WgAnswers from "./wg-comments/wg-answers.vue";
Vue.component("wg-answers", WgAnswers);
import WgAnswer from "./wg-comments/wg-answer.vue";
Vue.component("wg-answer", WgAnswer);
import WgFilterAd from "./wg-filters/wg-filter-ad.vue";
Vue.component("wg-filter-ad", WgFilterAd);
